//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vueling.Common.Logic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonLiterals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonLiterals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vueling.Common.Logic.CommonLiterals", typeof(CommonLiterals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseAddress.
        /// </summary>
        internal static string BaseAddKey {
            get {
                return ResourceManager.GetString("BaseAddKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionString.
        /// </summary>
        internal static string ConnectionKey {
            get {
                return ResourceManager.GetString("ConnectionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string Dot {
            get {
                return ResourceManager.GetString("Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfiguredAccessType.
        /// </summary>
        internal static string FactoryFormat {
            get {
                return ResourceManager.GetString("FactoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoggerFramework.
        /// </summary>
        internal static string LogggerKey {
            get {
                return ResourceManager.GetString("LogggerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MimeTypeHeader.
        /// </summary>
        internal static string MimeHeaderKey {
            get {
                return ResourceManager.GetString("MimeHeaderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedisEndpoint.
        /// </summary>
        internal static string RedisKey {
            get {
                return ResourceManager.GetString("RedisKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utils.
        /// </summary>
        internal static string Utils {
            get {
                return ResourceManager.GetString("Utils", resourceCulture);
            }
        }
    }
}
